version: "3"
services:
  telegram2elasticgui:
    build:
      context: git@github.com:Oriundi/Telegram2ElasticGUI.git
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
      - "5000:5000"
    volumes:
      - "./config/:/app/config"
networks:
  t2e:
    driver: bridge
